### ISSUE TITLE
tiktok config

### ISSUE THREAD

**Issue by netwet** [go-olive/olive#104]
hi. im use olive_v0.5.0_windows_amd64. im trying config tiktok and i got error:
` snap failed, Failed to fetch room ID by username: Your IP or country might be blocked by TikTok.`
after that i got random files like "config-1667205063.toml" in dir where olive.exe
how to get room id from tiktok? i know how to find "id" from streamer. my config file must be in zarf/tmpl?

**Comment by luxcgo** [comment]
1. "config-1667205063.toml" is auto generated config file
2. id is the `@xxx` part from the live url
3. no, it doesn't have to be.  use `olive run -f path/to/config.toml`
