### ISSUE TITLE
douyin live

### ISSUE THREAD

**Issue by yerawell** [go-olive/olive#106]
![0d91a68fd4204fd953b1ec15243307f](https://user-images.githubusercontent.com/64144095/199254240-1f6a6648-6620-4ebd-bf6d-7d0a1a53036c.jpg)
this mistake happened here, it shows that it couldn't snap douyin right now?

**Comment by luxcgo** [comment]
You could use `olive tv -u https://xxx`  to test if you can retrieve the live info.
It works for me locally, probably your ip is banned or your cookie is obsolete.

**Comment by JadeChaos** [comment]
@luxcgo I see the same error, can you help to debug? Or teach me how to check if my ip is banned, or cookie is obsolete? Thank you!

INFO[2022-11-22 23:35:50] dispatch add monitor                          id=136999369331 pf=douyin
INFO[2022-11-22 23:35:50] dispatch remove recorder                      id=136999369331 pf=douyin
INFO[2022-11-22 23:35:50] monitor start                                 id=136999369331 pf=douyin
TRAC[2022-11-22 23:35:50] snap failed, fail to find url                 id=136999369331 pf=douyin
INFO[2022-11-22 23:35:50] split program starts...
INFO[2022-11-22 23:35:50] parser-monitor program starts...

**Comment by JadeChaos** [comment]
btw, the bilibili works well.
And I see there's command biliup to generate cookie for bili, is there such command for douyin too?
