### ISSUE TITLE
docker部署网页版，其中olive-server和olive-portal无法启动

### ISSUE THREAD

**Issue by IndigoMagic** [go-olive/olive#109]
安装过程：
![image](https://user-images.githubusercontent.com/37242294/200286331-4ddf216c-5ea4-4e4d-acc0-e03bb1309986.png)
安装环境：群晖NAS 
其中olive-server错误日志：
**2022-11-07T10:09:45.535088668Z	stdout	{"level":"error","ts":"2022-11-07T18:09:45.534+0800","caller":"command/server.go:108","msg":"startup","service":"OLIVE-API","ERROR":"maxprocs: open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"}**
olive-portal错误日志：
**2022-11-07T10:10:06.941984680Z | stderr | nginx: [emerg] host not found in upstream "olive-server" in /etc/nginx/conf.d/default.conf:11
2022-11-07T10:10:06.941796497Z | stderr | 2022/11/07 10:10:06 [emerg] 1#1: host not found in upstream "olive-server" in /etc/nginx/conf.d/default.conf:11**

docker-compose.yaml文件（改了端口号是因为端口被占用）：
```
version: "3.8"

services:
  olive-db:
    image: postgres:14-alpine
    container_name: olive-db
    restart: always
    ports:
      - 127.0.0.1:8432:8432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - olive-network

  olive-server:
    image: luxcgo/olive:latest
    container_name: olive-server
    depends_on:
      - olive-db
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:4000:4000
    command:
      [
        "./olive",
        "server",
        "--db-host",
        "olive-db:8432",
        "-l",
        "/downloads",
        "-s",
        "/downloads",
      ]
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./downloads:/downloads
      - ./config:/config
    networks:
      - olive-network

  olive-portal:
    image: luxcgo/olive-portal:latest
    container_name: olive-portal
    depends_on:
      - olive-server
    ports:
      - "8080:8080"
    # volumes:
    #   - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - olive-network

networks:
  olive-network:

```

**Comment by wwkk2580** [comment]
一个一个启动，不要一起

**Comment by 2284787774** [comment]
一样的问题请问解决了吗

**Comment by IndigoMagic** [comment]
没有呢

**Comment by damian0321** [comment]
多是贼个问题

**Comment by JasonLongBug** [comment]
我也是这个问题，请问解决了吗

**Comment by MOLIzhang** [comment]
同maxprocs: open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 仍未解决

**Comment by luxcgo** [comment]
已支持，可下载最像镜像

**Comment by 2284787774** [comment]
> 已支持，可下载最像镜像

最新版olive-server启动完还是会报错

{"level":"info","ts":"2023-02-02T20:48:49.268+0800","caller":"command/server.go:123","msg":"starting service","service":"OLIVE-API","version":"0.5.1-nas"}
{"level":"info","ts":"2023-02-02T20:48:49.268+0800","caller":"command/server.go:130","msg":"startup","service":"OLIVE-API","config":"--read-timeout=20s\n--write-timeout=0s\n--idle-timeout=0s\n--shutdown-timeout=0s\n--api-host=0.0.0.0:3000\n--debug-host=0.0.0.0:4000\n--user=postgres\n--password=xxxxxx\n--host=olive-db:5432\n--name=postgres\n--max-idle-conns=0\n--max-open-conns=0\n--disable-tls=true"}
{"level":"info","ts":"2023-02-02T20:48:49.268+0800","caller":"command/server.go:138","msg":"startup","service":"OLIVE-API","status":"initializing database support","host":"olive-db:5432"}
{"level":"info","ts":"2023-02-02T20:51:06.756+0800","caller":"command/server.go:154","msg":"shutdown","service":"OLIVE-API","status":"stopping database support","host":"olive-db:5432"}
{"level":"info","ts":"2023-02-02T20:51:06.756+0800","caller":"command/server.go:162","msg":"shutdown complete","service":"OLIVE-API"}
{"level":"error","ts":"2023-02-02T20:51:06.756+0800","caller":"command/server.go:106","msg":"startup","service":"OLIVE-API","ERROR":"migrating database: migrate database: status check database: context deadline exceeded"}
