### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by BearChu** [go-olive/olive#110]
olive run -f "H:\olive\zarf\tmpl\config.toml"
[31mERRO[0m[2022-11-10 01:58:31] streamer not supported
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xd8 pc=0x78ec75]

goroutine 24 [running]:
github.com/go-olive/olive/engine/kernel.(*bout).Refresh(0x0)
        /home/runner/work/olive/olive/engine/kernel/bout.go:65 +0x55
github.com/go-olive/olive/engine/kernel.(*bout).AddMonitor(0x0)
        /home/runner/work/olive/olive/engine/kernel/bout.go:228 +0x1e
github.com/go-olive/olive/engine/kernel.(*Kernel).Run.func1({0x0?, 0x0?}, {{0x0, 0x0}, 0x0, {0xc0007ca350, 0x5}, {0xc0007ca360, 0x7}, {0x0, ...}, ...})
        /home/runner/work/olive/olive/engine/kernel/kernel.go:123 +0x85
github.com/go-olive/olive/foundation/syncmap.(*RWMap[...]).Each(0x0?, 0xc000691fa8?)
        /home/runner/work/olive/olive/foundation/syncmap/syncmap.go:48 +0x1b5
github.com/go-olive/olive/engine/kernel.(*Kernel).Run(0xc0005081c0)
        /home/runner/work/olive/olive/engine/kernel/kernel.go:118 +0x49
github.com/go-olive/olive/command.(*runCmd).run.func2()
        /home/runner/work/olive/olive/command/run.go:128 +0x1d
created by github.com/go-olive/olive/command.(*runCmd).run
        /home/runner/work/olive/olive/command/run.go:127 +0x1d9

**Comment by zerodq2019** [comment]
请问你的问题是怎么解决的？

**Comment by NoodlesStamps** [comment]
我在Docker上运行它，我也得到了同样的错误。
我想知道解决方案是什么。
