### ISSUE TITLE
config文件的一些设置问题和powershell下的颜色显示

### ISSUE THREAD

**Issue by KNaiFen** [go-olive/olive#114]
如下图，大佬能否解决一下呢，这一堆[36m属实把我真的有点晕
还有就是config文件的例子能否提供多几例呢？多几个不同平台的，齐全一点，还有很多选项也没注释，不知道啥意思，我都是看英文猜的，又怕猜错，感觉目前一上来都不太会用
还有就是web界面目前只能docker运行吗？有别的办法吗？
![image](https://user-images.githubusercontent.com/53338804/201507412-961cb990-274e-466f-a87c-a7c4b5db0f37.png)

**Comment by luxcgo** [comment]
1. `�[36m` 这个是颜色字符，可以用个现代点儿的终端会更好的显示。
2. 配置的话官网写的很详细了吧，https://go-olive.github.io/docs/guide/config/ 。
3. 当然可以本地运行，不过docker是最简单的。

**Comment by KNaiFen** [comment]
鹅很遗憾的是windows server2019貌似不能装terminl，我要换的话或许只能给服务器换系统了
然后配置的话，我就是看着官网来输的，Enable = false是什么东西？我以为是开关录播的选项，但是false和true貌似都不反应
还有ytdlp和ffmpeg这俩下载器用法都是跟streamlink一样吗？都是Platform = "streamlink"，RoomID = “直播间链接”这样吗？
单个主播的OutTmpl的输出文件名的.flv是可以改的吗？还是根据不同下载器有不同的变化？可选项是flv，mp4，ts？
Parser = "streamlink"可以用吗？还是只能按照实例那样来用？我不太明白

**Comment by luxcgo** [comment]
0. 目前终端颜色的话应该是支持win10之后的版本，不过我没有windows机器，测试不了
1. `Enable = false`这个是网页端用的，命令行版本的不用管
2. `streamlink`是独立的，只有它填的是链接
3. 目前改不了格式，需要自己转封装

**Comment by KNaiFen** [comment]
好的了解了，这个issue可以关掉了🆗，蟹蟹大佬解答
