### ISSUE TITLE
能不能做个详细视频教程或者啥的

### ISSUE THREAD

**Issue by vitkid** [go-olive/olive#116]
没有基础的人根本没法装，或者装了运行不了

**Comment by zgcanfly** [comment]
或者在BiliBili 录制一个使用视频 也可以哇

**Comment by gororo111** [comment]
只要能用命令行 olive run -u +url 这一步完成就完成一大半了，现在我的是可以录制，然后需要再运行一次才可以上传b站，  效果很好的，不过有时候因为直播主自身网络问题，如果帧数太低，会转码失败，无法上传

**Comment by wangnan789** [comment]
> 没有基础的人根本没法装，或者装了运行不了
这里有详细说明
https://go-olive.github.io/docs/guide/intro/
