### ISSUE TITLE
$FILE_PATH加了/bin/zsh", "-c"还是解析不出来,大佬帮忙看看什么原因

### ISSUE THREAD

**Issue by passerby-b** [go-olive/olive#119]
[[Shows]]
Platform = "douyin"
RoomID = "wu284814691"
StreamerName = "打螺丝"
Parser = "flv"
#SaveDir = "./douyin"
[[Shows.PostCmds]]
Path = "oliveshell"
Args = ["/bin/zsh", "-c", "echo $FILE_PATH"]

time="2022-11-29 11:55:00" level=error msg="exec: \"/bin/zsh\": file does not exist" filepath="D:\\olive_v0.3.3_windows_amd64\\[打螺丝][生化职业选手在线秀操作][2022-11-29 11-54-37].flv" postCmdArgs="/bin/zsh -c echo $FILE_PATH" postCmdPath=

日志提示这个文件没有,但是这个文件是有的

**Comment by UVJkiNTQ** [comment]
Windows上没有zsh吧……

**Comment by passerby-b** [comment]
百度搜说windows是要装那个linux子系统吗?

**Comment by gororo111** [comment]
我的解决方法就是把你的windows的bash地址打上去

**Comment by gororo111** [comment]
> 百度搜说windows是要装那个linux子系统吗?

不用装那个wsl，我也是用的windows bash的位置
