### ISSUE TITLE
Go1.20下无法编译

### ISSUE THREAD

**Issue by qchenac** [go-olive/olive#134]
- 系统：Mac OS 13.2.1
- CPU：M1
- GO版本：1.20.1 darwin/arm64

安装时报错如下：
`# github.com/imroc/req/v3/internal/qtls
go/pkg/mod/github.com/imroc/req/v3@v3.25.0/internal/qtls/go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
 github.com/lucas-clemente/quic-go/internal/qtls
go/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.1/internal/qtls/go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration`
好像是quic-go版本太低？我看quic-go0.33.0已经支持go1.20了

**Comment by lwb-2021** [comment]
@luxcgo 为什么安装时还是这样报错
