### ISSUE TITLE
no command olive found

### ISSUE THREAD

**Issue by wwjqmy** [go-olive/olive#14]
大佬好，我没学过编程自己瞎弄的。用的termux想用备用手机录下直播，安装olive应该是安装了，显示了go：downloading github.com/巴拉巴拉/olive v0.2.8 但是运行olive就no command。是啥原因呢

**Comment by luxcgo** [comment]
你可以使用绝对路径试下，找不到的原因可能是环境变量里面没有

**Comment by 0zxcvbnm0** [comment]
这程序怎么使用啊，以管理员身份运行olive.exe应用程序，命令窗口一闪而过，还有直播源在哪个文件里添加，能录个小白使用教程吗？
