### ISSUE TITLE
Tiktok broken API

### ISSUE THREAD

**Issue by spinningsand** [go-olive/olive#143]
I've had a couple issues I was wanted to solve but I don't know if you were still addressing them or not.

**Comment by spinningsand** [comment]
It isn't working on tiktok at all anymore. I have the latest version, but it stopped working today. I just get a message saying they're offline and it's doing to every live I've tried it on.

EDIT: Got it to work on 1 live, but it hasn't worked on anything else I've tried, so it does barely work.

**Comment by spinningsand** [comment]
Also, when I tried upgrading to the newest version, I get this message:

```
go: downloading github.com/go-olive/olive v0.5.2
go: github.com/go-olive/olive@latest: github.com/go-olive/olive@v0.5.2: verifying module: checksum mismatch
        downloaded: h1:xlTDXxfmISEUriGC+lANuZHBrGhBCaHK0CpFU4L1+js=
        sum.golang.org: h1:awAjnl3qHcHSQinNrjGiExC9TSPhWS1xEjwU9Wxjjgk=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I dunno if this has anything to do with it not working on tiktok.

**Comment by spinningsand** [comment]
I dunno if you're gonna read or solve this, but I'll mention it anyway. It apparently does seem to still work, it just takes a minute and several snap attempts to get it to start recording. It's easier to get it to work in some lives than others.

**Comment by spinningsand** [comment]
Well now, it doesn't seem to be recording at all now for real. I've waited 20+ minutes and can't get it to work anymore. Even if it does eventually work, it takes way too long to get started and isn't practical to use anymore. I don't know what's going on with it or why it takes forever to work.

**Comment by spinningsand** [comment]
It appears TikTok is blocking the requests somehow now. When I use it, it sometimes says my IP or country might be blocked.

**Comment by luxcgo** [comment]
I implemented new methods for tiktok. You can try the new version.
