### ISSUE TITLE
youtube无法录制。已经在配置文件中加了代理，貌似没生效。浏览器是能访问油管的。配置文件如下

### ISSUE THREAD

**Issue by neuralfork** [go-olive/olive#145]
[Config]
PortalUsername = 'olive'
PortalPassword = 'olive'
LogDir = 'D:\software_download\olive_v0.5.2_windows_amd64'
SaveDir = 'D:\software_download\olive_v0.5.2_windows_amd64'
OutTmpl = '[{{ .StreamerName }}][{{ .RoomName }}][{{ now | date "2006-01-02 15-04-05"}}].flv'
LogLevel = 5
SnapRestSeconds = 15
SplitRestSeconds = 60
CommanderPoolSize = 1
ParserMonitorRestSeconds = 300
BiliupEnable = false
CookieFilepath = ''
Threads = 0
MaxBytesPerSecond = 0.0
[[Envs]]
Key = 'https_proxy'
Value = 'http://127.0.0.1:7890'
[[Envs]]
Key = 'http_proxy'
Value = 'http://127.0.0.1:7890'

[[Shows]]
ID = ''
Enable = false
Platform = 'youtube'
RoomID = 'UCOSmkVK2xsihzKXQgiXPS4w'
StreamerName = '油管'
OutTmpl = ''
Parser = 'streamlink'
SaveDir = ''
PostCmds = ''
SplitRule = ''
DateCreated = 0001-01-01T00:00:00Z
DateUpdated = 0001-01-01T00:00:00Z

**Comment by luxcgo** [comment]
0.5 版本已取消代理的配置项
0.5.3 修复了 YouTube 的 api 问题
可以运行命令后 `olive run -u https://www.youtube.com/@LofiGirl` 查看本地新生成的配置文件格式
