### ISSUE TITLE
youtube直播录制创建文件失败。tiktok,bilibili录制正常。

### ISSUE THREAD

**Issue by neuralfork** [go-olive/olive#147]
C:\olive_v0.5.3_windows_amd64
λ olive run -u https://www.youtube.com/@HistoryBro100
INFO[2023-06-26 23:08:35] dispatch add monitor                          id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:36] dispatch remove recorder                      id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:36] monitor start                                 id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:37] live status changed                           id=@HistoryBro100 new=true old=false pf=youtube
INFO[2023-06-26 23:08:37] dispatch add recorder                         id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:37] recorder start                                id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:37] dispatch remove monitor                       id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:37] split program starts...
INFO[2023-06-26 23:08:37] parser-monitor program starts...
INFO[2023-06-26 23:08:37] monitor stop                                  id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:40] record start                                  id=@HistoryBro100 pf=youtube rn="�Live  【週一晚上8點】雙主修吃播訂起來！無題懂的都懂！ ft. 黃士修｜歷史哥Talk 112.6.26"
DEBU[2023-06-26 23:08:41] streamlink working                            out="C:\\olive_v0.5.3_windows_amd64\\[油管][�Live  【週一晚上8點】雙主修吃播訂起來！無題懂的都懂！ ft. 黃士修｜歷史哥Talk 112.6.26][2023-0
ERRO[2023-06-26 23:08:41] rm small file failed(stat): CreateFile C:\olive_v0.5.3_windows_amd64\[油管][�Live  【週一晚上8點】雙主修吃播訂起來！無題懂的都懂！ ft. 黃士修｜歷史哥Talk 112.6.26][2023-06-26 23-08-40]
.mp4: The system cannot find the file specified.
INFO[2023-06-26 23:08:41] dispatch add monitor                          id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:41] dispatch remove recorder                      id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:41] monitor start                                 id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:43] live status changed                           id=@HistoryBro100 new=true old=false pf=youtube
INFO[2023-06-26 23:08:43] dispatch add recorder                         id=@HistoryBro100 pf=youtube
INFO[2023-06-26 23:08:43] recorder start                                id=@HistoryBro100 pf=youtube
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x39450d]

goroutine 82 [running]:
os.(*Process).signal(0xc0001b18c0?, {0xd86180?, 0x1261df8?})
        /opt/hostedtoolcache/go/1.20.5/x64/src/os/exec_windows.go:49 +0x4d
os.(*Process).Signal(...)
        /opt/hostedtoolcache/go/1.20.5/x64/src/os/exec.go:138
os.(*Process).kill(...)
        /opt/hostedtoolcache/go/1.20.5/x64/src/os/exec_posix.go:67
os.(*Process).Kill(...)
        /opt/hostedtoolcache/go/1.20.5/x64/src/os/exec.go:123
github.com/go-olive/olive/engine/parser.(*streamlink).Parse(0xc000132660, {0xc0000307b0, 0x2b}, {0xc002bb2240, 0xb8})
        /home/runner/work/olive/olive/engine/parser/streamlink.go:61 +0x32c
github.com/go-olive/olive/engine/recorder.(*recorder).record(0xc00013c4d0)
        /home/runner/work/olive/olive/engine/recorder/recorder.go:184 +0xd50
github.com/go-olive/olive/engine/recorder.(*recorder).run(0xc00013c4d0)
        /home/runner/work/olive/olive/engine/recorder/recorder.go:215 +0xb1
created by github.com/go-olive/olive/engine/recorder.(*recorder).Start
        /home/runner/work/olive/olive/engine/recorder/recorder.go:56 +0xf0

**Comment by neuralfork** [comment]
tiktok无提示错误。但文件夹中看不到创建的flv文件。国内平台正常

**Comment by luxcgo** [comment]
![image](https://github.com/go-olive/olive/assets/73606679/c6ebddf9-0444-4787-a54c-ddcfd59f42fd)
看报错是你本地没安装 streamlink 吧

**Comment by neuralfork** [comment]
ok,解决了！
