### ISSUE TITLE
视频录制漏录

### ISSUE THREAD

**Issue by passerby-b** [go-olive/olive#15]
大佬,我用这个工具录虎牙直播,星期五开启的,星期六的能录制,星期天的就没有,遇到过好几次,平时每天下班时开启录屏,第二天上班来手动关了,下班时再开就没问题,如果连续开几天不关中间就会漏录,win10 64位系统

time="2022-05-30 09:03:30" level=info msg="record stop: exit status 0xc000013a" id=77927 pf=huya
time="2022-05-30 09:03:30" level=info msg="recorder stop" id=77927 pf=huya
time="2022-05-30 09:03:30" level=info msg="monitor stop" id=77927 pf=huya

**Comment by luxcgo** [comment]
方便的话可以上传一下日志文件`a.log`，顺便说一下开启时间，和中间的哪一天哪个主播漏了

**Comment by luxcgo** [comment]
是中间漏了，后面又好了吗。会不会主播偷懒没播。

**Comment by passerby-b** [comment]
[a.log](https://github.com/go-olive/olive/files/8796080/a.-.log)
星期五六点左右开的,星期六的能录制,星期天的漏了,每次都是星期天漏了,后面不知道好没好,因为我星期一上班手动关了,昨天肯定是开播了我看了的,房间号520902

**Comment by luxcgo** [comment]
`time="2022-05-28 22:11:23" level=debug msg="ffmpeg working" out="[2022-05-28 22-11-23][阿涵][嘿嘿].flv"`

`time="2022-05-30 09:03:30" level=info msg="handle request" signal=terminated
time="2022-05-30 09:03:30" level=info msg="record stop: exit status 0xc000013a" id=520902 pf=huya
time="2022-05-30 09:03:30" level=info msg="recorder stop" id=520902 pf=huya
time="2022-05-30 09:03:30" level=info msg="monitor stop" id=520902 pf=huya`

这两条日志显示是在`2022-05-28 22:11:23`这个时间点`FFmpeg`开始录制，直到`2022-05-30 09:03:30`手动关闭才停止。
应该是`FFmpeg`在直播流结束后没有正确的停止。这个在其他软件中也有出现过，是`FFmpeg`的问题。

**Comment by luxcgo** [comment]
你的`Parser`可以用我自研的`flv`试一下，应该就没有这个问题。

**Comment by passerby-b** [comment]
好的,多谢大佬
