### ISSUE TITLE
chat recording available?

### ISSUE THREAD

**Issue by vioan** [go-olive/olive#152]
Hi,

is there any option to record the live chat as well? As I see currently I can only record the video, and the chat is empty.

**Comment by luxcgo** [comment]
not available

**Comment by Geczy** [comment]
@luxcgo what does it take to add chat recording? would love this option

can we use the tiktok library to record chat with this too?

**Comment by Geczy** [comment]
we can see it like this: https://github.com/Davincible/gotiktoklive#ChatEvent

**Comment by vioan** [comment]
any improvements on this feature request?
