### ISSUE TITLE
snap failed, send http request failed 录制失败

### ISSUE THREAD

**Issue by wangnan789** [go-olive/olive#155]
INFO[2023-09-14 21:41:33] dispatch add monitor                          id=xxxxxxx pf=douyin
INFO[2023-09-14 21:41:33] dispatch remove recorder                      id=xxxxxxx pf=douyin
INFO[2023-09-14 21:41:33] monitor start                                 id=xxxxxxx pf=douyin
TRAC[2023-09-14 21:41:33] snap failed, send http request failed: Get "https://live.douyin.com/xxxxxxx": proxyconnect tcp: dial tcp 127.0.0.1:7890: connect: connection refused  id=xxxxxxx pf=douyin
INFO[2023-09-14 21:41:33] split program starts...                      
INFO[2023-09-14 21:41:33] parser-monitor program starts...             
TRAC[2023-09-14 21:41:48] snap failed, send http request failed: Get "https://live.douyin.com/xxxxxxx": proxyconnect tcp: dial tcp 127.0.0.1:7890: connect: connection refused  id=xxxxxxx pf=douyin
TRAC[2023-09-14 21:41:58] snap failed, send http request failed: Get "https://live.douyin.com/xxxxxxx": proxyconnect tcp: dial tcp 127.0.0.1:7890: connect: connection refused  id=xxxxxxx pf=douyin

**Comment by wangnan789** [comment]
我发现只有运行[clash](https://github.com/zzzgydi/clash-verge) （不管是否开启代理），就能成功录制

**Comment by luxcgo** [comment]
![image](https://github.com/go-olive/olive/assets/73606679/d10efb1d-bd58-4ae4-8e8c-1141b4ef7db6)
是因为你本地环境变量的配置
