### ISSUE TITLE
`ffmpeg` doesn't exist on docker image

### ISSUE THREAD

**Issue by Geczy** [go-olive/olive#156]
can you add it please and update the image?

<img width="279" alt="image" src="https://github.com/go-olive/olive/assets/1036968/c8c1d2da-64d6-4eec-9166-3f40387734d3">

**Comment by Geczy** [comment]
i added it to docker like this https://github.com/Geczy/olive/commit/7c96f0963b44b81e67156ab665996101c8174c53

**Comment by luxcgo** [comment]
Sure, added it on v0.6.0.

**Comment by Geczy** [comment]
thx!!
