### ISSUE TITLE
不能录制，似乎是网路问题，但ping又是正常的,而且浏览器也正常

### ISSUE THREAD

**Issue by wangnan789** [go-olive/olive#162]
./olive  run -f 079-778017889747_二胡.toml 
INFO[2023-10-04 21:50:06] dispatch add monitor                          id=778017889747 pf=douyin
INFO[2023-10-04 21:50:06] dispatch remove recorder                      id=778017889747 pf=douyin
INFO[2023-10-04 21:50:06] monitor start                                 id=778017889747 pf=douyin
INFO[2023-10-04 21:50:07] live status changed                           id=778017889747 new=true old=false pf=douyin
INFO[2023-10-04 21:50:07] dispatch add recorder                         id=778017889747 pf=douyin
INFO[2023-10-04 21:50:07] recorder start                                id=778017889747 pf=douyin
INFO[2023-10-04 21:50:07] dispatch remove monitor                       id=778017889747 pf=douyin
INFO[2023-10-04 21:50:07] parser-monitor program starts...             
INFO[2023-10-04 21:50:07] monitor stop                                  id=778017889747 pf=douyin
INFO[2023-10-04 21:50:07] split program starts...                      
ERRO[2023-10-04 21:50:07] snap failed, Get "https://live.douyin.com/778017889747": dial tcp: lookup live.douyin.com on 192.168.1.1:53: no such host  cnt=1 id=778017889747 pf=douyin
ERRO[2023-10-04 21:50:12] snap failed, Get "https://live.douyin.com/778017889747": dial tcp: lookup live.douyin.com on 192.168.1.1:53: no such host  cnt=2 id=778017889747 pf=douyin
ERRO[2023-10-04 21:50:17] snap failed, Get "https://live.douyin.com/778017889747": dial tcp: lookup live.douyin.com on 192.168.1.1:53: no such host  cnt=3 id=778017889747 pf=douyin
ERRO[2023-10-04 21:50:17] rm small file failed(stat): stat : no such file or directory 
INFO[2023-10-04 21:50:17] dispatch add monitor                          id=778017889747 pf=douyin
INFO[2023-10-04 21:50:17] dispatch remove recorder                      id=778017889747 pf=douyin
INFO[2023-10-04 21:50:17] monitor start                                 id=778017889747 pf=douyin
TRAC[2023-10-04 21:50:17] snap failed, Get "https://live.douyin.com/778017889747": dial tcp: lookup live.douyin.com on 192.168.1.1:53: no such host  id=778017889747 pf=douyin
TRAC[2023-10-04 21:50:35] snap failed, Get "https://live.douyin.com/778017889747": dial tcp: lookup live.douyin.com on 192.168.1.1:53: no such host  id=778017889747 pf=douyin

**Comment by lanzxAccount** [comment]
我也是报一样的错误，网页版是被阉割了吗

**Comment by luxcgo** [comment]
这个看着就是 dns 配置的问题，从域名解析不出来 ip
