### ISSUE TITLE
无法启动抖音直播录制

### ISSUE THREAD

**Issue by iwestlin** [go-olive/olive#170]
应该是从今天下午开始失效的，`olive tv -u ...` 也无法输出直链地址

**Comment by iwestlin** [comment]
https://github.com/gagaprince/smart_photo/commit/d86684c910544d6c49e4a555f3fa9dd147091437
https://github.com/ToxicStar8/DouYinLiveFetchToUnity/commit/d7368057cf6980398a525096b9b975d6d97612e2
这两个commit好像是相关的……

**Comment by iwestlin** [comment]
这里还有个更简单的修复方式：https://github.com/auqhjjqdo/LiveRecorder/commit/8dbea01eed688b182d5b15e63f760f76b4c9558f

**Comment by 0zxcvbnm0** [comment]
这程序怎么使用啊，以管理员身份运行olive.exe应用程序，命令窗口一闪而过，还有直播源在哪个文件里添加，能录个小白使用教程吗？在b站找教程，也没找到！

**Comment by luxcgo** [comment]
> 这里还有个更简单的修复方式：[auqhjjqdo/LiveRecorder@8dbea01](https://github.com/auqhjjqdo/LiveRecorder/commit/8dbea01eed688b182d5b15e63f760f76b4c9558f)

已按照这个修复

**Comment by iwestlin** [comment]
多谢，验证成功

**Comment by iwestlin** [comment]
> 这程序怎么使用啊，以管理员身份运行olive.exe应用程序，命令窗口一闪而过，还有直播源在哪个文件里添加，能录个小白使用教程吗？在b站找教程，也没找到！

这是个命令行程序，没有图形界面的，需要在命令行运行，你可以搜一下命令行的教程。。
