### ISSUE TITLE
empty text error

### ISSUE THREAD

**Issue by LDQONJ** [go-olive/olive#173]
![image](https://github.com/go-olive/olive/assets/128981031/d2b30ca7-7534-4950-9a41-3be0fab0f25a)

![image](https://github.com/go-olive/olive/assets/128981031/c66d8dd6-a457-4305-a210-1346556ed1e5)
这里的text经常为空。

**Comment by qchenac** [comment]
同

**Comment by LDQONJ** [comment]
应该是cookie的ttwid获取不到，手动加上浏览器的cookie可以正常运行

**Comment by luxcgo** [comment]
更新了下获取 ttwid 的方法

**Comment by LDQONJ** [comment]
现在获取text所需的cookie好像不是ttwid了，变成sid_tt了

**Comment by qchenac** [comment]
> 现在获取text所需的cookie好像不是ttwid了，变成sid_tt了

是需要在cookie里添加sid_tt吗

**Comment by LDQONJ** [comment]
> > 现在获取text所需的cookie好像不是ttwid了，变成sid_tt了
> 
> 是需要在cookie里添加sid_tt吗

我的cookie只填浏览器cookie里的sid_tt就可以
![`@HKTJVWZYB@U{CK~KX$EG4](https://github.com/go-olive/olive/assets/128981031/5baa9e1a-2354-4b41-b333-245621cbafd3)

**Comment by LDQONJ** [comment]
现在又可以用ttwid了，6.3可以正常录制了
