### ISSUE TITLE
fix a replay source bug

### ISSUE THREAD

**Issue by wangbjun** [go-olive/olive#174]
https://github.com/go-olive/olive/blob/edd387ba6125a5b8f490f4bc1037e9ee7f6d6dd5/foundation/olivetv/huya.go#L71C1-L72C1

虎牙的直播源加密方式经常变，找了很多发现只有这个库是可以用的，借鉴了一下，作者辛苦了，不过这块代码有一点点小问题，这个u是未decode的字符串，当是直播间是重放的时候，应该用decodedURL拼接地址。

**Comment by luxcgo** [comment]
能提供个测试的 url 吗？ 重放的有点难找。
或者你确定的话直接提 pr 也可以。

**Comment by wangbjun** [comment]
你试试这2个直播间，重播的时候都有问题发自我的 iPhone在 2024年1月9日，10:46，luxcgo ***@***.***> 写道：﻿
能提供个测试的 url 吗？ 重放的有点难找。
或者你确定的话直接提 pr 也可以。

**Comment by luxcgo** [comment]
哪两个？没发出来吧。

**Comment by wangbjun** [comment]
不好意思，图片没发出去，我重新贴一下
![d3a0e9177ca842573b8562e9a07abdf](https://github.com/go-olive/olive/assets/39372433/6f8794d3-1ee1-4cd0-9834-8aafe123ac23)

你可以试试虎牙直播间991111、uzi等正在重播的直播间，都是没有获取成功
