### ISSUE TITLE
youtube-roomid相关问题

### ISSUE THREAD

**Issue by mbskter** [go-olive/olive#2]
#关于channelURL := fmt.Sprintf("https://www.youtube.com/channel/%s", s.RoomID)

目前youtube的直播url应该是https://www.youtube.com/watch?v=IDxxxxx

**Comment by hackcraker** [comment]
这里的 channelURL 指的是频道的 url，
例如 https://www.youtube.com/channel/UC7QVieoTCNwwW84G0bddXpA
youtube 的直播 url 是动态变化的，而频道的 url 是固定不变的
所以在配置文件中填写频道ID，主播开播时会自动侦测到直播 url 并开始录制

**Comment by luxcgo** [comment]
这里的 channelURL 指的是频道的 url，
例如 https://www.youtube.com/channel/UC7QVieoTCNwwW84G0bddXpA
youtube 的直播 url 是动态变化的，而频道的 url 是固定不变的
所以在配置文件中填写频道ID，主播开播时会自动侦测到直播 url 并开始录制

**Comment by mbskter** [comment]
明白了，谢谢大佬！！！

**Comment by mbskter** [comment]
done
