### ISSUE TITLE
虎牙录屏容易花屏

### ISSUE THREAD

**Issue by passerby-b** [go-olive/olive#20]
![20220625092045](https://user-images.githubusercontent.com/40885345/175752917-a191ee08-f33b-450c-b7d3-eb04ce0d1ed3.png)
麻烦大佬看看什么情况?

**Comment by luxcgo** [comment]
这种情况多出现于户外主播，主要特点是他们的直播流不稳定，视频的一些基础配置项会改变。
导致后续的视频仍按照前面视频的配置进行错误的解析，出现花屏。

目前 [olive](https://github.com/go-olive/olive/) 没有内置视频修复的功能，不过你可以尝试用 https://rec.danmuji.org/user/toolbox/repair/ 这个工具修复下试试。
