### ISSUE TITLE
为单独show配置上传开关/脚本执行

### ISSUE THREAD

**Issue by UVJkiNTQ** [go-olive/olive#24]
1. 目前的upload是global选项，是否可以为每个show单独配置？

    建议简易实现：global选项(开)+show配置黑名单(上传开关)。

    工程量大的实现：为每个show单独配置一个上传profile，适应于多个专有录播账号。

2. 之前执行shell的issue漏提了，由于备份目录的不同，为了减少复杂度，建议为每个[show]指定单独的shell运行配置。
   否则可能要多吐一个主播名字作为判断依据，shell再根据这个名字选择执行不同命令，可能会复杂一点。

**Comment by luxcgo** [comment]
A1: 可以的，这块内容已经重构了。到时候上传功能会作为一个插件的存在，每个`show`可以选择是否添加。

A2: 已实现，==我写个详细的说明。
