### ISSUE TITLE
B站录播开始时持续生成小文件，导致起始缺2分钟~30分钟不等

### ISSUE THREAD

**Issue by UVJkiNTQ** [go-olive/olive#32]
![image](https://user-images.githubusercontent.com/12570945/178111916-db8eaa5b-0a8c-43c4-b815-f9f9bbf4dabd.png)

**Comment by UVJkiNTQ** [comment]
实际19_05_01开始的
![PA0JHSJIDZU%GV294KFT)H8](https://user-images.githubusercontent.com/12570945/178112074-f49825d7-8420-4fe1-b67c-48640bb1d9e6.png)

**Comment by UVJkiNTQ** [comment]
[ll.txt](https://github.com/go-olive/olive/files/9079179/ll.txt)

**Comment by luxcgo** [comment]
`olive`目前是没有修复系统的，服务器给什么数据就录下来什么数据。

不过小文件会自动删除，我看你的这些文件只有`owner`才有写权限，能看看你的`olive程序`所属的用户组是什么吗，怀疑是权限问题没有删掉。

**Comment by UVJkiNTQ** [comment]
olive我用的就是这个user开了个tmux在shell跑的，所以权限是没问题。
看来是获取的源的问题了……那些13Byte文件的时间的录播就全丢了。

**Comment by luxcgo** [comment]
好的，之前的那个名称长度切割的问题新版本已经修复了，最长允许255个字节。

之后我在删除文件那块加个log吧，看看到底是啥问题。

**Comment by jkfujr** [comment]
碎片问题
一般情况是 [b站自建的地方运营商cdn](https://rec.danmuji.org/dev/bilibili-cdn/) 引起的，多发的重复数据
如果能连上腾讯云的cdn，如 [d1--cn-gotcha04.bilivideo.com](https://rec.danmuji.org/dev/bilibili-cdn/#d1--cn-gotcha04.bilivideocom) 的话，基本就不存在碎的问题。


解决碎片问题
1.稳定连上04，也就是腾讯云的cdn
要稳定连上04可以用腾讯云的轻量云去反代b站的请求api `https://api.live.bilibili.com/` 回来给家宽用。
为啥不用轻量云录，因为个人录的多，如果就几个，你可以直接用轻量云。
（[api搭建参考](https://docs.qq.com/doc/DV2dvbXBrckNscU9x) (里有公共api，由腾讯云cdn转发，回源ip非常多))

2.录制hls流
web观看b站直播是使用的hls流的cdn，
录制的话，目前只见过 [blrec](https://github.com/acgnhiki/blrec) 能录制hls流，不过经录播姬群友的使用体验，资源占用比较高(应该是转码)，稳定性存疑


个人使用反代api
目前要同时挂的直播间有200+，还需要抓取全程的弹幕sc礼物，目前录播姬加反代算是比较成熟
