### ISSUE TITLE
抖音直播间无法打开

### ISSUE THREAD

**Issue by BlackTravel** [go-olive/olive#33]
各位师傅，昨天试用了一天，今天的所有直播间已经无法打开，日志显示time="2022-07-10 07:18:34" level=info msg="handle request" signal=terminated，这种情况是如何产生的

**Comment by luxcgo** [comment]
这日志的意思是你把程序给关闭了……

**Comment by BlackTravel** [comment]
我现在打开抖音直播间的网址，显示是空白的

**Comment by BlackTravel** [comment]
https://live.douyin.com/314319524794，我打开这个网址啥也没用，账号登录也是空白，但是手机端可以观看

**Comment by luxcgo** [comment]
截个图看看，另外你用无痕模式试一下呢

**Comment by BlackTravel** [comment]
![QQ截图20220710114521](https://user-images.githubusercontent.com/65138134/178130465-3494e6ff-94c4-4893-8271-77288f1435e1.jpg)

**Comment by luxcgo** [comment]
这看着是你本地网络环境的问题吧，是不是开了代理啥的

**Comment by BlackTravel** [comment]
网站主页可以进得去，https://live.douyin.com/     ，这个网页没问题，但是直播间进不去
