### ISSUE TITLE
录制不了Youtube

### ISSUE THREAD

**Issue by SeaL773** [go-olive/olive#35]
streamlink已安装 cmd已设置代理 curl google 有返回信息
用的快速启动 olive -u https://www.youtube.com/channel/频道id
返回[36mINFO[0m[2022-07-17 20:01:02] dispatch add monitor                          [36mid[0m=频道id[36mpf[0m=youtube
[36mINFO[0m[2022-07-17 20:01:02] dispatch remove recorder                      [36mid[0m=频道id[36mpf[0m=youtube
[36mINFO[0m[2022-07-17 20:01:02] monitor start                                 [36mid[0m=频道id[36mpf[0m=youtube
然后就没反应了 twitch也是一样

试过录哔哩哔哩  虎牙可以正常运行

**Comment by SeaL773** [comment]
streamlink版本[streamlink-4.2.0-1-py310-x86_64.exe]
python版本3.10
path已添加

**Comment by luxcgo** [comment]
![image](https://user-images.githubusercontent.com/73606679/179401158-8827afdb-2a48-46f6-b6ac-100aa8f50fc2.png)

我本地试了下都正常。

**Comment by luxcgo** [comment]
建议直接使用streamlink录制下，看看是否正常。

**Comment by UVJkiNTQ** [comment]
多半是代理设置的问题
我也录youtube，没有问题

**Comment by SeaL773** [comment]
已解决 代理设置问题
