### ISSUE TITLE
[站点支持]请求支持快手平台直播录制

### ISSUE THREAD

**Issue by TeslaLyon** [go-olive/olive#4]
请求支持快手平台直播录制

**Comment by luxcgo** [comment]
已支持

**Comment by luxcgo** [comment]
目前测试的结果快手的 cookie 不能复用，只能在录制的机器上获取。且一定时间后会过期。

**Comment by luxcgo** [comment]
经实际测试，快手的 cookie 失效的比较快，且可能在使用 cookie 时需要保证网页端保持登陆的状态。
可以先使用这个库 github.com/go-olive/tv 检测一下 cookie 是不是真的还在可用的状态。
目前没有什么好的方法自动获取有效的 cookie，普通手段获取的 cookie 都无法使用。

**Comment by TeslaLyon** [comment]
感谢反馈，我目前是手动录制，用的这个包：https://pypi.org/project/you-live/  这个包厉害。。 cookie 最低经历一个月不会提示过期。。 

原谅我的 golang 不够浪。。 目前帮不上忙。。

**Comment by luxcgo** [comment]
实际上我们用的都是一个API，只不过他是一次性的，我这里要不断的轮询以判断开播状态。可能是这个原因导致被风控了，我现在换了一种方法，从主播详情页获取消息，会好一些。
