### ISSUE TITLE
好像对douyin平台失效了

### ISSUE THREAD

**Issue by kanwairen1234** [go-olive/olive#41]
今天发现无法录制了，之前还可以。。。

**Comment by luxcgo** [comment]
未复现。

可以做以下尝试：

1. 是否使用的最新版本
2. 更换直播间是否正常
3. 更换cookie是否正常

**Comment by kanwairen1234** [comment]
IP问题，我是用的一台online独服，同样的配置文件，cookie都没换，换了其他机器好的，这台昨天还好好的，今天就不行，折腾了老半天，累。

**Comment by kanwairen1234** [comment]
是不是因为我加了太多room id程序请求太频繁导致IP被限制，我大概加了7-8个抖音id

**Comment by luxcgo** [comment]
很有可能，tiktok 都有类似的风控
可以适当调整这个配置

![image](https://user-images.githubusercontent.com/73606679/180172685-6ce74c8c-7eea-482a-9dc8-037a0981f13d.png)

**Comment by tuxi** [comment]
我测试了下douyin，一直在`monitor start `不动了，这个roomId也是有效的
$ ./olive -f src/tmpl/config.toml 
INFO[2022-07-21 19:10:32] Powered by go-olive/olive v0.3.1             
INFO[2022-07-21 19:10:32] dispatch add monitor                          id=7122771219427478285 pf=douyin
INFO[2022-07-21 19:10:32] dispatch remove recorder                      id=7122771219427478285 pf=douyin
INFO[2022-07-21 19:10:32] monitor start                                 id=7122771219427478285 pf=douyin

**Comment by tuxi** [comment]
我发觉我对这个roomID有误解，我用到的是主播真实的roomID，换成分享链接后面的id就可以录制了
