### ISSUE TITLE
无奖问答

### ISSUE THREAD

**Issue by luxcgo** [go-olive/olive#43]
请问这个项目对你有帮助吗？你有什么推荐的直播给大伙吗？

如果觉得这个项目还不错的话，能不能动一动小手，点一个免费的小星星呢 ･ᴗ･

**Comment by jkfujr** [comment]
好，点了捏
![仙贝](https://s1.ax1x.com/2022/07/22/jOGgVP.jpg)

**Comment by daxiaamo** [comment]
我推荐一个韩国的平台AfreecaTV，网址 afreecatv.com 有很多好看的韩国小姐姐还有很多很有名的韩国电竞选手，不知道是否可以加入录制支持。😜
