### ISSUE TITLE
使用streamlink录制YouTube直播时报错

### ISSUE THREAD

**Issue by Highsunlight** [go-olive/olive#57]
使用yt-dlp就可以正常录制并保存文件

麻烦大佬看一下

<img width="1006" alt="屏幕截图 2022-07-25 154310" src="https://user-images.githubusercontent.com/69392777/180724567-b00864fa-7757-4d4d-a367-3c71bdb844fc.png">

**Comment by luxcgo** [comment]
这种你直接用 streamlink 录制下看报什么错就好了。

**Comment by jkfujr** [comment]
~~会限？~~
紫菜，没注意前面标题

**Comment by Highsunlight** [comment]
还是搞不懂，但是可以通过更换为yt-dlp来解决

那就关闭了吧，谢谢解答
