### ISSUE TITLE
使用yt-dlp录制YouTube直播结束距生成mp4文件有长时间延迟

### ISSUE THREAD

**Issue by Highsunlight** [go-olive/olive#58]
使用配置文件进行录制，下载器为yt-dlp

开始录制时间为00:10:02 UTC

结束录制时间为01:12:07 UTC

而直播时长只有25分38秒

直播结束后有一个后缀名为.part的文件，时长和录制结束生成的mp4文件时长一致

也就是产生了30多分钟的延迟

我负责几个管人字幕组的录播，30多分钟的延迟对于激光烤肉的影响还是比较大的（）

希望佬可以解决一下
<img width="391" alt="屏幕截图 2022-07-25 154859" src="https://user-images.githubusercontent.com/69392777/180727192-53acf6a7-34dd-419e-9fec-1f1c43dc7350.png">
<img width="975" alt="屏幕截图 2022-07-25 154922" src="https://user-images.githubusercontent.com/69392777/180727207-6a9c756f-3778-4ff2-bb90-61453c35afa4.png">

**Comment by luxcgo** [comment]
我看原视频似乎也就这么长？
只差了十几秒，是因为监控不是实时的，有个间歇。

**Comment by Highsunlight** [comment]
呃，没有啊，视频不到半小时，但是从录制开始到录制结束是62分钟

一般来说这种直播激光全熟整个处理时间就3个小时左右，包括打轴翻译校对压制发布，延迟半个小时算是比较长了
目前是保存在本地，后期要挂载webdav到cloudreve上，这个延迟还是很厉害的，麻烦佬再看下（）

**Comment by luxcgo** [comment]
明白你的意思了。实现上来说是直播结束录制就会结束的。
我怀疑这种情况是视频结束后，直播流并未结束，所以还是在录制状态。直到主播断流了，才判断是直播结束。

**Comment by jkfujr** [comment]
尝试加个数据检测？

**Comment by luxcgo** [comment]
> 尝试加个数据检测？

是个思路。

这种还是很好实现的，和切分文件类似。

**Comment by luxcgo** [comment]
这种情况出现的次数多吗？一般都是多久延迟。

**Comment by Highsunlight** [comment]
不确定，分情况，时短时长，目前还在观察，等我这边看看下再向你说下（）

我这边用rclone挂载OneDrive盘到服务器上，有时会无缘无故跑出大于视频文件几十倍的流量，上下行有异常的流量，怀疑和这个有关系

**Comment by luxcgo** [comment]
有出现过单场直播多个重复录制的情况吗？

**Comment by Highsunlight** [comment]
有的，基本只发生过刚才这一次
<img width="974" alt="image" src="https://user-images.githubusercontent.com/69392777/183713461-3927316f-e570-493c-b58c-c55b52c73f65.png">

**Comment by luxcgo** [comment]
ok，这个其实不是我说的情况。这个还是顺序录制的，只录了一次，没有重复，中间断了可能是网络或其他问题。

**Comment by Highsunlight** [comment]
刚才出现了重复录制的情况

从本地和OneDrive上看都有两个文件，但SSH里输出是只有录制一个
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/69392777/183853322-878640e5-d035-480f-8b03-13037397a5e0.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/69392777/183854100-45902bdd-bb99-447b-8d1a-108298f1c4de.png">

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/69392777/183853418-25e55ac0-4c65-4f9f-9611-68129a137657.png">

**Comment by luxcgo** [comment]
emm, 这个看起来跟 olive 没关系，是 yt-dlp 那边的问题。。。
