### ISSUE TITLE
请问是如何实现 监测youtube直播状态 的

### ISSUE THREAD

**Issue by 2845525241** [go-olive/olive#6]
如题 我目前想到的是反复请求 youtube data api 或 访问频道的直播页面 
或者 通过pubsubhubbub 接收到新的推送 再 请求api或直播页面 

我不懂go 也不太会使用 github 若滥用了 issues 我也很抱歉 
实在是不知道该问谁了

**Comment by luxcgo** [comment]
可以参考这里 https://github.com/go-olive/tv/blob/a7abc988daaab6c9984066357cf1905ff525507c/youtube.go#L35-L44
请求官方提供的 API 的话需要申请账号什么的很麻烦，不方便大家使用，所以我是直接定时爬取网页端的内容来判断的。
