### ISSUE TITLE
请问作者 关于一些参数的问题

### ISSUE THREAD

**Issue by NormanMises** [go-olive/olive#61]
作者大大 如果我想按 2022-04-24 02-02-32 的格式输出文件那我的date 后的参数应该怎么写啊 
我按Linux的格式写了` {{ date "+%Y-%m-%d %H-%M-%S" }} `结果无法识别 
您的doc里也没有写明格式 只写了个具体时间例子 能否补全一下标准格式呢？

**Comment by jkfujr** [comment]
如下
`{{ now | date \"2006-01-02 15-04-05\"}}`

**Comment by NormanMises** [comment]
卧槽好快 我试试
对了
LogLevel = 5
SnapRestSeconds = 15
这两句是啥意思呀

**Comment by jkfujr** [comment]
LogLevel 日志等级
SnapRestSeconds 应该是监控录制间隔，单位应该是秒

**Comment by NormanMises** [comment]
我还以为 那个`|`是或的意思🤣

**Comment by NormanMises** [comment]
好嘞 谢谢~~

**Comment by jkfujr** [comment]
> 我还以为 那个`|`是或的意思🤣

可能参考了这个https://liquid.bootcss.com/basics/introduction/

**Comment by NormanMises** [comment]
哦哦我来研究下

**Comment by jkfujr** [comment]
不过能用的也就README里的

- `OutTmpl` 文件名称
  - `{{ now | date \"2006-01-02 15-04-05\"}}` 录制日期
  - `{{ .StreamerName }}` 主播名称
  - `{{ .RoomName }}` 直播标题
- `SaveDir` 文件保存位置
  - `{{ now | date \"2006-01-02 15-04-05\"}}` 录制日期

示例
```
[[Shows]]
Platform = "youtube"
RoomID = "UCrhx4PaF3uIo9mDcTxHnmIg"
StreamerName = "Paryi"
SaveDir = "E:/Video/录播/P家/{{ now | date \"20060102-150405\"}}/Paryi/youtube"
OutTmpl = "{{ now | date \"20060102-150405\"}}_{{ .RoomName }}【{{ .StreamerName }}】.flv"
```

输出
```
E:/Video/录播/P家/20220729-000000/Paryi/yourube/20220729-000000_标题【Paryi】
```

**Comment by NormanMises** [comment]
嗯嗯这样就够了
我现在在尝试把flv自动转成MP4 用ffmpeg

**Comment by jkfujr** [comment]
#56 在下面我已经建议做全局的文件路径以及文件名了，可以更简洁点

**Comment by NormanMises** [comment]
```
[Shows.SplitRule]
Filesize = 50000000
```
发现切分好像不太准确 是`SnapRestSeconds = 10`的影响吗

**Comment by jkfujr** [comment]
> ```
> [Shows.SplitRule]
> Filesize = 50000000
> ```
> 
> 发现切分好像不太准确 是`SnapRestSeconds = 10`的影响吗

嗯..这个没用过，拿个直播间测试下吧

**Comment by NormanMises** [comment]
嗯 不过还好没啥影响

**Comment by NormanMises** [comment]
请问 录制结束后执行定制化命令 中的自定义命令该怎么写呀？
我想通过ffmpeg把flv文件自动打包成MP4文件
Windows怎么进shell环境呢 就像doc中的`/bin/zsh`
```
[[Shows.PostCmds]]
Path = "D:/Apps/ffmpeg/bin/"
Args = ["ffmpeg.exe", "-i", "$FILE_PATH", "-c", "copy", "-copyts", "$FILE_PATH.mp4"]
```
尝试了好几种写法都不成功
![image](https://user-images.githubusercontent.com/38835726/181678310-329ed01c-33d2-40fe-be04-5971c0d451dd.png)
