### ISSUE TITLE
olivearchive 功能无法使用

### ISSUE THREAD

**Issue by NormanMises** [go-olive/olive#62]
![屏幕截图 2022-07-30 181849](https://user-images.githubusercontent.com/38835726/181907657-320b4376-1f5d-4151-a636-cfc163cbfe61.png)
如图 在添加了
```
[[Shows.PostCmds]]
Path = "olivearchive"
```
功能后执行时不论`SaveDir`的文件夹下有无’archive‘这个文件夹都无法正常执行，看提示是使用了`rename`？怎么是重命名呀，不应该是`mv`或`move`吗

**Comment by luxcgo** [comment]
golang 的内库 os 里面并没有 move 的函数，所以用的都是 rename 。

**Comment by luxcgo** [comment]
需要兼容 windows 环境

**Comment by NormanMises** [comment]
哦哦
