### ISSUE TITLE
Room ID for YouTube and StreamLink Question

### ISSUE THREAD

**Issue by hl2guide** [go-olive/olive#63]
Does the room ID need to be set for YouTube monitoring?

My current config (config.toml):

```
[[Shows]]
# platform name
Platform = "youtube"
# room id
RoomID = ""
# streamer name
StreamerName = "thejimmydoreshow"
SaveDir = "C:/Temp/olive-streams"
Parser = "streamlink"
```

When using streamlink do I simply need it to be available to CMD (Windows Environment Variable: PATH)?

**Comment by luxcgo** [comment]
A1. Yes, it is a necessity. And it ought to be the channelID.
![image](https://user-images.githubusercontent.com/73606679/182007896-5555d922-4d47-4b4a-9970-0ae71bce90bf.png)

A2. Yes.
