### ISSUE TITLE
Output File Format

### ISSUE THREAD

**Issue by hl2guide** [go-olive/olive#64]
Please consider changing the output format from FLV to MP4 or MKV.

This will improve tracking and also show a thumbnail in File Explorer.

**Comment by luxcgo** [comment]
There are a few things need to be clarified.
First, the video format is the same as the original stream. It doesn't depend on me, If your want a different format, you can always do that yourself using `ffmpeg`.
Second, the `flv` is nothing merely a filename. In other words, it probably is a mp4 file simply using `flv` as a filename suffix.

**Comment by sxx1314** [comment]
> There are a few things need to be clarified. First, the video format is the same as the original stream. It doesn't depend on me, If your want a different format, you can always do that yourself using `ffmpeg`. Second, the `flv` is nothing merely a filename. In other words, it probably is a mp4 file simply using `flv` as a filename suffix.

I recently found out that using streamlink to record videos defaults to mp4 format, but the extension is flv. This is very inconvenient, and if I use a script to automatically change the extension, I still have to check whether the current file is finished recording. I looked at the code, and I’m not familiar with go. Wouldn’t it be better to add a judgment and directly output mp4 extension?

https://github.com/go-olive/olive/blob/02fb3b9f3abac34879530d2fa858ecc1f2a4d11e/engine/recorder/recorder.go#L166-L173
