### ISSUE TITLE
对于YouTube短链接如何填写RoomID进行录制

### ISSUE THREAD

**Issue by Highsunlight** [go-olive/olive#66]
有的YouTube频道会启用短链接形式，譬如
https://www.youtube.com/c/KurenagiEri
https://www.youtube.com/clearusui

而目前olive支持的是下面形式的长链接
https://www.youtube.com/channel/UCgF7nAJ85yIopVHSheUaYsw
https://www.youtube.com/channel/UCg3tKEUFef2R-wQ-hRahkiQ

想问下这样如何录制（）

另外问下
<img width="960" alt="image" src="https://user-images.githubusercontent.com/69392777/183682899-fbc6088b-3f49-43fe-9b07-a1172459bf03.png">
有正常的录播输出，但是因为什么原因报错，是字面意思吗，是否影响其他功能

**Comment by luxcgo** [comment]
A1. https://github.com/go-olive/olive/issues/63#issuecomment-1200337047

A2. 不影响。只是录播结束后的三次校验确保确实已经下播，只是一个日志。

**Comment by Highsunlight** [comment]
已解决，谢谢
