### ISSUE TITLE
境外服务器无法录制YouTube直播

### ISSUE THREAD

**Issue by Highsunlight** [go-olive/olive#68]
不好意思，又来打扰大佬了x，但确实出了问题

RT，服务器在vultr的东京机房，系统为Ubuntu 20.04
发布issue时以下三个频道都在直播
https://www.youtube.com/channel/UCwaS8_S7kMiKA3izlTWHbQg
https://www.youtube.com/channel/UC3uoOH4N2F4T9FyAGDwM6Ow
https://www.youtube.com/channel/UCIG9rDtgR45VCZmYnd-4DUw

但SSH输出中并没有录制的状态
<img width="841" alt="image" src="https://user-images.githubusercontent.com/69392777/184107742-03532b01-62ee-40ec-b5da-9ac038674828.png">
只有一个用来测试b站直播间在正常录制

请问是否是olive的问题，或者有没有可能是服务器的ip被Google ban掉了？

另外想提点建议，我看到文档中给出的配置文件有以下部分
<img width="662" alt="image" src="https://user-images.githubusercontent.com/69392777/184108382-a41fffca-16ee-4960-8553-7df7987dd353.png">
![image](https://user-images.githubusercontent.com/69392777/184108397-ff0def87-3a01-4235-8e09-d406e2932de7.png)
给否给出相关的说明，如果可以就非常感谢了

**Comment by luxcgo** [comment]
![image](https://user-images.githubusercontent.com/73606679/184112500-73496b39-7613-4f09-bf3d-85c8747648b1.png)

本地测试正常。

建议先测试网络，再直接使用相应的软件直接录制试试。

**Comment by luxcgo** [comment]
配置文件的话

1. 网站 cookie，变量名就能看出来
2. 全局变量，用于帮助一些用户配置代理的
3. https://github.com/go-olive/olive/discussions/60

**Comment by Highsunlight** [comment]
好的，感谢回复

刚才看了下，似乎被Google ban了

curl命令请求了下，有这样的回复
<img width="967" alt="image" src="https://user-images.githubusercontent.com/69392777/184120279-e657c84d-0af2-4cee-931d-403b07fca271.png">
http://www.google.com/sorry/index?continue=http://youtube.com/&amp;q=EhAgARnwcAEOJFQAA__-5q32GOzD05cGIhBNjMEH1uoXJ22SDKWKQqvrMgFy

等一会看看能不能恢复罢（）

**Comment by Highsunlight** [comment]
恢复了，还真是被ban了（）

希望给后来的各位能提个醒，Google确实会因为异常流量禁止的（）
