### ISSUE TITLE
录制问题求解 

### ISSUE THREAD

**Issue by lbcake** [go-olive/olive#72]
1.请问这几个参数具体代表什么
LogLevel = 5
SnapRestSeconds = 15
SplitRestSeconds = 60
CommanderPoolSize = 1
ParserMonitorRestSeconds = 300

2.streamlink 为什么不开启录制  下了win的构建 该嵌入的都嵌入了

![image](https://user-images.githubusercontent.com/26319880/184509890-559d5d08-cd13-4948-9ccb-f896951963d0.png)
![image](https://user-images.githubusercontent.com/26319880/184509891-017f71d3-fbe6-4cc8-a4b6-1a3a84857db7.png)

没有开启录制

图中config没有加SaveDir    我也测试了加SaveDir 同样没有开启录制  请问streamlink具体现在要怎么写设置

**Comment by luxcgo** [comment]
A1. https://github.com/go-olive/olive/blob/main/README_ZH.md#configtoml

A2. 可以直接使用streamlink录制下看日志，`streamlink -o "test.mp4" 填入url -f`
