### ISSUE TITLE
希望在Shows.PostCmds里面也可以使用{{ .StreamerName }}

### ISSUE THREAD

**Issue by huang1332** [go-olive/olive#75]
比如
[[Shows.PostCmds]]
Path = "oliveshell"
Args = [ "python3","re.py","{{ .StreamerName }}"]
这样方便录制之后的处理

**Comment by luxcgo** [comment]
录制结束后对文件做处理的话不是只需要文件路径即可吗，不太明白你需要这个变量有什么作用。

**Comment by huang1332** [comment]
> 录制结束后对文件做处理的话不是只需要文件路径即可吗，不太明白你需要这个变量有什么作用。

比如把日期作为参数传进去的话，录制之后的自动上传脚本就可以把日期加到视频简介上
我目前在用视频文件名提取日期之类的信息，好像也还算稳定
那就先不改吧，不好意思
