### ISSUE TITLE
关于保存位置上日期参数的逻辑问题

### ISSUE THREAD

**Issue by jkfujr** [go-olive/olive#81]
![1](https://user-images.githubusercontent.com/39889850/189493532-93a96f14-a364-4df8-9b8f-5923315ae732.png)

`SaveDir = "E:/Video/录播/{{ now | date \"20060102\"}}/{{ .StreamerName }}/twitch/{{ now | date \"20060102-150405\"}}_标题【{{ .StreamerName }}】/"`

开播后，时间变更就会新建文件夹。

**Comment by luxcgo** [comment]
这个是在尝试获取直播流，跟时间变更没关系
