### ISSUE TITLE
貌似抖音不能录播了

### ISSUE THREAD

**Issue by passerby-b** [go-olive/olive#82]
之前是可以录的,配置文件都没改过,最近不能录了

**Comment by luxcgo** [comment]
未复现，测试正常。

有可能是cookie过期了，或是SnapRestSeconds(监控间隔)过小被风控。

**Comment by passerby-b** [comment]
[a.log](https://github.com/go-olive/olive/files/9650861/a.log)
[config.txt](https://github.com/go-olive/olive/files/9650864/config.txt)
cookie换了也不行,家里和公司的网络都试了不行

**Comment by passerby-b** [comment]
而且试了olivetv获取不到抖音的直播源地址

**Comment by passerby-b** [comment]
olivetv也获取不到抖音直播源地址

**Comment by luxcgo** [comment]
因为我有录了几个抖音，每天都会上传到B站，所以我这看是正常的。

你有录几个人，获取不到的原因大概率是风控原因，你直接上网站上看应该也是白屏。

**Comment by luxcgo** [comment]
监控间隔太短的话有几个群友也有类似的问题。

**Comment by luxcgo** [comment]
还有就是你的版本有更到最新吗，之前抖音数据结构改了。

![image](https://user-images.githubusercontent.com/73606679/192419295-e3dbdda7-568c-42c1-8c53-34b69b5ec878.png)

**Comment by passerby-b** [comment]
olivetv是0.3.0版的,0.3.1版没看到有window是版,olive是0.3.3版的,我的网页播放是正常的,我写了一个nodejs版是可以录播视频的https://github.com/passerby-b/douyin_record/blob/main/douyin_down.js

**Comment by luxcgo** [comment]
是你的版本太旧了。。

**Comment by luxcgo** [comment]
![image](https://user-images.githubusercontent.com/73606679/192420903-23ead298-8e77-49af-b1bb-f57a2c6c7aa9.png)
日志都说是 0.3.2

![image](https://user-images.githubusercontent.com/73606679/192421031-b2ad2b59-c7a9-4448-989c-04d2cadb3dba.png)
抖音的修复是在 0.3.3

**Comment by luxcgo** [comment]
olivetv 一般我有点懒的打 tag
不过后续会有大版本更新，会融合进一个项目。而且支持 k8s 。

**Comment by passerby-b** [comment]
sorry,没点show all version版本,还以为新版没有windows版,打扰大佬了
