### ISSUE TITLE
一个YouTube频道有多个直播流的时候 录制不了

### ISSUE THREAD

**Issue by SeaL773** [go-olive/olive#84]
如题，今天想录一个企业YouTube号的直播，一个channel同时存在四个直播流
![Screenshot_2022-10-01-11-56-27-992-edit_com google android youtube](https://user-images.githubusercontent.com/34188323/193386623-10fed8fd-61b2-4b93-b10b-95c0720b0d65.jpg)

软件无法识别哪个直播流需要录制，无法开始录制

**Comment by SeaL773** [comment]
可以增加识别房间号录制? 一般这种直播会提前一天或者几小时开启预约，会生成一个独有的房间号，可以用steamlink抓直播流录制。
不知道这种情况多不多，房间号感觉没有特别好的思路获取，可以间隔一段时间发个包，看有没有新的直播预约，然后获取房间号?如果获取到多个的话同时录制?会不会对vps的带宽要求过高?

**Comment by luxcgo** [comment]
暂不支持一个YouTube频道多个直播流的情况
