### ISSUE TITLE
douyin ban IP

### ISSUE THREAD

**Issue by horizonsw** [go-olive/olive#90]
Hi. 关于"SnapRestSeconds":100 ，定义的是每100s执行全局直播间状态查询吗？这可能是频繁触发风控的原因之一，能否额外添加参数定义到达“SnapRestSeconds”时间后，直播间状态查询的间隔时间，即查询1个直播间状态后sleep 1~2s再执行下一个，尝试规避风控；

**Comment by luxcgo** [comment]
不是全局查询，是每个直播间到了时间执行自己的。

每个直播间是独立掌管自己的时间的且增加了随机参数，现在的实现不是像你说的这种。
