### ISSUE TITLE
twitch的直播无法保存 报错rm small file failed(stat)

### ISSUE THREAD

**Issue by mikufoxxx** [go-olive/olive#92]
time="2022-10-22 23:57:50" level=info msg="Powered by go-olive/olive v0.3.3"
time="2022-10-22 23:57:50" level=info msg="dispatch add monitor" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="dispatch remove recorder" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="monitor start" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="live status changed" id=saadhak new=true old=false pf=twitch
time="2022-10-22 23:57:50" level=info msg="dispatch add recorder" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="recorder start" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="dispatch remove monitor" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="monitor stop" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=info msg="parser-monitor program starts..."
time="2022-10-22 23:57:50" level=info msg="record start" id=saadhak pf=twitch rn="LOUD Saadhak | Sabadou !pix"
time="2022-10-22 23:57:50" level=debug msg="streamlink working" out="/home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-50].flv"
time="2022-10-22 23:57:50" level=info msg="record stop: exit status 1" id=saadhak pf=twitch
time="2022-10-22 23:57:50" level=error msg="rm small file failed(stat): stat /home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-50].flv: no such file or directory"
time="2022-10-22 23:57:50" level=info msg="record start" id=saadhak pf=twitch rn="LOUD Saadhak | Sabadou !pix"
time="2022-10-22 23:57:50" level=debug msg="streamlink working" out="/home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-50].flv"
time="2022-10-22 23:57:51" level=info msg="record stop: exit status 1" id=saadhak pf=twitch
time="2022-10-22 23:57:51" level=error msg="rm small file failed(stat): stat /home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-50].flv: no such file or directory"
time="2022-10-22 23:57:51" level=info msg="record start" id=saadhak pf=twitch rn="LOUD Saadhak | Sabadou !pix"
time="2022-10-22 23:57:51" level=debug msg="streamlink working" out="/home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-51].flv"
time="2022-10-22 23:57:52" level=info msg="record stop: exit status 1" id=saadhak pf=twitch
time="2022-10-22 23:57:52" level=error msg="rm small file failed(stat): stat /home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-51].flv: no such file or directory"
time="2022-10-22 23:57:52" level=info msg="record start" id=saadhak pf=twitch rn="LOUD Saadhak | Sabadou !pix"
time="2022-10-22 23:57:52" level=debug msg="streamlink working" out="/home/[推趣][LOUD Saadhak _ Sabadou !pix][2022-10-22 23-57-52].flv"

**Comment by itrack** [comment]
+1

**Comment by luxcgo** [comment]
It means `streamlink` couldn't download the stream. Please try use streamlink first.
Btw, the latest docker version has streamlink embedded, you could try that as well.
