### ISSUE TITLE
docker如何食用

### ISSUE THREAD

**Issue by chenlu964** [go-olive/olive#95]
已下载docker文件了，但是我是群晖小白只会傻瓜图形化配置，能不能把那些文件变量和端口需要设置出一起教程贴呢（最好保姆级），让大伙都能使用上，再次感谢大佬

**Comment by 1lovejkovo** [comment]
docker run -itd --name olive -P luxcgo/olive 跑了一遍
等到docker ps的时候发现没有上来
-d选项拿掉以后运行同样也是直接掉了

**Comment by luxcgo** [comment]
https://go-olive.github.io/docs/guide/usage/#docker%e7%89%88%e6%9c%ac

可以参考下这个

**Comment by luxcgo** [comment]
> docker run -itd --name olive -P luxcgo/olive 跑了一遍 等到docker ps的时候发现没有上来 -d选项拿掉以后运行同样也是直接掉了

需要重写 command 命令的，和挂载下载目录

**Comment by luxcgo** [comment]
群里有大佬是用群晖跑起来的，可以进群问问。

docker命令可以参考下面这个
```sh
docker run -v ./downloads:/downloads -v ./config:/config —name olive-run luxcgo/olive:latest ./olive run -f /config/config.toml 
```

**Comment by chenlu964** [comment]
好的 我晚上回去试试

**Comment by wzgrx** [comment]
> 群里有大佬是用群晖跑起来的，可以进群问问。
> 
> docker命令可以参考下面这个
> 
> ```shell
> docker run -v ./downloads:/downloads -v ./config:/config —name olive-run luxcgo/olive:latest ./olive run -f /config/config.toml 
> ```

>docker run -v ./downloads:/downloads -v ./config:/config —name olive-run luxcgo/olive:latest ./olive run -f /config/config.toml
docker: invalid reference format.
See 'docker run --help'.
