### ISSUE TITLE
docker网页版的server获取时区出错，没有+8

### ISSUE THREAD

**Issue by wwkk2580** [go-olive/olive#99]
![1667141472691](https://user-images.githubusercontent.com/76099203/198885198-cd367552-2096-4af0-9e57-7c35b62f2802.png)
会导致视频的时间出错

**Comment by wwkk2580** [comment]
我的宿主机是windows的

**Comment by luxcgo** [comment]
时区的话应该要把本机的时区挂载进去。我没设置默认的时区是中国。
